# Generated by Django 3.2.7 on 2021-09-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210926_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
        ),
    ]
