# Generated by Django 3.2.7 on 2021-09-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210930_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
