# Generated by Django 3.2.7 on 2021-10-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210930_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='danger',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
