# Generated by Django 3.2.7 on 2021-10-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_danger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='danger',
        ),
    ]
