# Generated by Django 3.2.7 on 2021-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_category_danger'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='danger',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
