# Generated by Django 3.2.7 on 2021-10-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_relen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relen',
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default=None, upload_to='Relen'),
            preserve_default=False,
        ),
    ]
