# Generated by Django 3.2.7 on 2021-10-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211014_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='images',
        ),
    ]
