# Generated by Django 3.2.7 on 2021-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211014_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='relen',
            name='image_hov',
            field=models.ImageField(default=None, upload_to='relen'),
            preserve_default=False,
        ),
    ]
