# Generated by Django 3.2.8 on 2021-10-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_relen_image_hov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relen',
            name='image_hov',
        ),
    ]
