# Generated by Django 3.2.8 on 2021-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_relen_image_hov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('xabar', models.TextField()),
            ],
        ),
    ]
