# Generated by Django 3.2.8 on 2021-10-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_postm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ism',
        ),
        migrations.DeleteModel(
            name='PostM',
        ),
    ]
