# Generated by Django 3.2.8 on 2021-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211021_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='relen_product',
            field=models.ManyToManyField(blank=True, null=True, to='main.relen'),
        ),
    ]
